<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="17" passed="5" failed="0" skipped="12">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-20T13:58:25 IST" name="Automation Suite" finished-at="2025-05-20T13:58:35 IST" duration-ms="10133">
    <groups>
    </groups>
    <test started-at="2025-05-20T13:58:25 IST" name="Zygal Connect Mobile App Test Cases" finished-at="2025-05-20T13:58:35 IST" duration-ms="10133">
      <class name="Test.loginPageTest">
        <test-method signature="loginWithValidCredentialsTest(org.testng.ITestContext)[pri:1, instance:Test.loginPageTest@58fb7731]" started-at="2025-05-20T13:58:25 IST" name="loginWithValidCredentialsTest" description="User Login with Valid Credentials" finished-at="2025-05-20T13:58:33 IST" duration-ms="7896" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@11eadcba]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithValidCredentialsTest -->
        <test-method signature="loginWithInvalidCredentialsTest(org.testng.ITestContext)[pri:2, instance:Test.loginPageTest@58fb7731]" started-at="2025-05-20T13:58:33 IST" name="loginWithInvalidCredentialsTest" finished-at="2025-05-20T13:58:33 IST" duration-ms="6" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@11eadcba]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping invalid login test as per config]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping invalid login test as per config
at Test.loginPageTest.loginWithInvalidCredentialsTest(loginPageTest.java:93)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidCredentialsTest -->
        <test-method signature="verifyEmptyUserEmail(org.testng.ITestContext)[pri:0, instance:Test.loginPageTest@58fb7731]" started-at="2025-05-20T13:58:33 IST" name="verifyEmptyUserEmail" description="Verify empty email state" finished-at="2025-05-20T13:58:33 IST" depends-on-methods="Test.loginPageTest.loginWithInvalidCredentialsTest" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Test.loginPageTest.verifyEmptyUserEmail() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.loginWithInvalidCredentialsTest() on instance Test.loginPageTest@58fb7731]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Test.loginPageTest.verifyEmptyUserEmail() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.loginWithInvalidCredentialsTest() on instance Test.loginPageTest@58fb7731]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyEmptyUserEmail -->
        <test-method signature="loginWithInvalidEmail(org.testng.ITestContext)[pri:0, instance:Test.loginPageTest@58fb7731]" started-at="2025-05-20T13:58:33 IST" name="loginWithInvalidEmail" description="Verify Login with Invalid Email" finished-at="2025-05-20T13:58:33 IST" depends-on-methods="Test.loginPageTest.verifyEmptyUserEmail" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Test.loginPageTest.loginWithInvalidEmail() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.verifyEmptyUserEmail() on instance Test.loginPageTest@58fb7731]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Test.loginPageTest.loginWithInvalidEmail() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.verifyEmptyUserEmail() on instance Test.loginPageTest@58fb7731]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidEmail -->
        <test-method signature="loginWithNotRegisteredEmail(org.testng.ITestContext)[pri:0, instance:Test.loginPageTest@58fb7731]" started-at="2025-05-20T13:58:33 IST" name="loginWithNotRegisteredEmail" description="Verify Login with Not Registred Email" finished-at="2025-05-20T13:58:33 IST" depends-on-methods="Test.loginPageTest.loginWithInvalidEmail" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Test.loginPageTest.loginWithNotRegisteredEmail() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.loginWithInvalidEmail() on instance Test.loginPageTest@58fb7731]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Test.loginPageTest.loginWithNotRegisteredEmail() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.loginWithInvalidEmail() on instance Test.loginPageTest@58fb7731]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithNotRegisteredEmail -->
        <test-method signature="verifyAdminViewerLoginBlock(org.testng.ITestContext)[pri:0, instance:Test.loginPageTest@58fb7731]" started-at="2025-05-20T13:58:33 IST" name="verifyAdminViewerLoginBlock" description="Verify admin viewer Shouldn&#039;t be able to login" finished-at="2025-05-20T13:58:33 IST" depends-on-methods="Test.loginPageTest.loginWithNotRegisteredEmail" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Test.loginPageTest.verifyAdminViewerLoginBlock() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.loginWithNotRegisteredEmail() on instance Test.loginPageTest@58fb7731]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Test.loginPageTest.verifyAdminViewerLoginBlock() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.loginWithNotRegisteredEmail() on instance Test.loginPageTest@58fb7731]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAdminViewerLoginBlock -->
        <test-method signature="loginwithWrongOTP(org.testng.ITestContext)[pri:0, instance:Test.loginPageTest@58fb7731]" started-at="2025-05-20T13:58:33 IST" name="loginwithWrongOTP" description="Verify Login with Wrong OTP" finished-at="2025-05-20T13:58:33 IST" depends-on-methods="Test.loginPageTest.verifyAdminViewerLoginBlock" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Test.loginPageTest.loginwithWrongOTP() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.verifyAdminViewerLoginBlock() on instance Test.loginPageTest@58fb7731]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Test.loginPageTest.loginwithWrongOTP() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.verifyAdminViewerLoginBlock() on instance Test.loginPageTest@58fb7731]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginwithWrongOTP -->
        <test-method signature="verifySameEmailOnOtpPage(org.testng.ITestContext)[pri:0, instance:Test.loginPageTest@58fb7731]" started-at="2025-05-20T13:58:33 IST" name="verifySameEmailOnOtpPage" description="Verify same email on OTP page" finished-at="2025-05-20T13:58:33 IST" depends-on-methods="Test.loginPageTest.loginwithWrongOTP" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Test.loginPageTest.verifySameEmailOnOtpPage() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.loginwithWrongOTP() on instance Test.loginPageTest@58fb7731]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Test.loginPageTest.verifySameEmailOnOtpPage() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.loginwithWrongOTP() on instance Test.loginPageTest@58fb7731]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySameEmailOnOtpPage -->
        <test-method signature="verifyAccountBlock(org.testng.ITestContext)[pri:0, instance:Test.loginPageTest@58fb7731]" started-at="2025-05-20T13:58:33 IST" name="verifyAccountBlock" description="Verify account block after attempting wrong OTP for 5 times" finished-at="2025-05-20T13:58:33 IST" depends-on-methods="Test.loginPageTest.verifySameEmailOnOtpPage" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Test.loginPageTest.verifyAccountBlock() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.verifySameEmailOnOtpPage() on instance Test.loginPageTest@58fb7731]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Test.loginPageTest.verifyAccountBlock() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.verifySameEmailOnOtpPage() on instance Test.loginPageTest@58fb7731]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAccountBlock -->
        <test-method signature="verifyGoToSignPage(org.testng.ITestContext)[pri:0, instance:Test.loginPageTest@58fb7731]" started-at="2025-05-20T13:58:33 IST" name="verifyGoToSignPage" description="Verify Go To Sign In page Navigation" finished-at="2025-05-20T13:58:33 IST" depends-on-methods="Test.loginPageTest.verifyAccountBlock" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Test.loginPageTest.verifyGoToSignPage() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.verifyAccountBlock() on instance Test.loginPageTest@58fb7731]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Test.loginPageTest.verifyGoToSignPage() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.verifyAccountBlock() on instance Test.loginPageTest@58fb7731]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyGoToSignPage -->
        <test-method signature="verifyAccountBlockOnGetOtpPage(org.testng.ITestContext)[pri:0, instance:Test.loginPageTest@58fb7731]" started-at="2025-05-20T13:58:33 IST" name="verifyAccountBlockOnGetOtpPage" description="Verify that navigation and getOTP blocked for blocked account" finished-at="2025-05-20T13:58:33 IST" depends-on-methods="Test.loginPageTest.verifyGoToSignPage" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Test.loginPageTest.verifyAccountBlockOnGetOtpPage() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.verifyGoToSignPage() on instance Test.loginPageTest@58fb7731]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Test.loginPageTest.verifyAccountBlockOnGetOtpPage() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.verifyGoToSignPage() on instance Test.loginPageTest@58fb7731]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAccountBlockOnGetOtpPage -->
        <test-method signature="verifyResendOTP(org.testng.ITestContext)[pri:0, instance:Test.loginPageTest@58fb7731]" started-at="2025-05-20T13:58:33 IST" name="verifyResendOTP" description="Verify Resend OTP button" finished-at="2025-05-20T13:58:33 IST" depends-on-methods="Test.loginPageTest.verifyAccountBlockOnGetOtpPage" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Test.loginPageTest.verifyResendOTP() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.verifyAccountBlockOnGetOtpPage() on instance Test.loginPageTest@58fb7731]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Test.loginPageTest.verifyResendOTP() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.verifyAccountBlockOnGetOtpPage() on instance Test.loginPageTest@58fb7731]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyResendOTP -->
        <test-method signature="verifyAccountBlockOnResendOtp(org.testng.ITestContext)[pri:0, instance:Test.loginPageTest@58fb7731]" started-at="2025-05-20T13:58:33 IST" name="verifyAccountBlockOnResendOtp" description="Verify account block after 5 times of resend otp" finished-at="2025-05-20T13:58:33 IST" depends-on-methods="Test.loginPageTest.verifyResendOTP" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Test.loginPageTest.verifyAccountBlockOnResendOtp() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.verifyResendOTP() on instance Test.loginPageTest@58fb7731]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Test.loginPageTest.verifyAccountBlockOnResendOtp() on instance Test.loginPageTest@58fb7731 depends on not successfully finished methods 
[Test.loginPageTest.verifyResendOTP() on instance Test.loginPageTest@58fb7731]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAccountBlockOnResendOtp -->
      </class> <!-- Test.loginPageTest -->
      <class name="Test.homePageTest">
        <test-method signature="verifyHomePageLoads(org.testng.ITestContext)[pri:0, instance:Test.homePageTest@aafcffa]" started-at="2025-05-20T13:58:33 IST" name="verifyHomePageLoads" description="Verify Home Page Loads Successfully" finished-at="2025-05-20T13:58:33 IST" depends-on-methods="Test.loginPageTest.loginWithValidCredentialsTest" duration-ms="24" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@11eadcba]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePageLoads -->
        <test-method signature="goToProfilePage(org.testng.ITestContext)[pri:0, instance:Test.homePageTest@aafcffa]" started-at="2025-05-20T13:58:33 IST" name="goToProfilePage" description="Navigate to Profile Page" finished-at="2025-05-20T13:58:33 IST" depends-on-methods="Test.homePageTest.verifyHomePageLoads" duration-ms="631" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@11eadcba]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToProfilePage -->
      </class> <!-- Test.homePageTest -->
      <class name="Test.profilePageTest">
        <test-method signature="verifyProfilePageLoad(org.testng.ITestContext)[pri:0, instance:Test.profilePageTest@6955cb39]" started-at="2025-05-20T13:58:33 IST" name="verifyProfilePageLoad" description=" Verify profile page loads" finished-at="2025-05-20T13:58:34 IST" depends-on-methods="Test.homePageTest.goToProfilePage" duration-ms="645" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@11eadcba]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProfilePageLoad -->
        <test-method signature="verifySuccessfulLogout(org.testng.ITestContext)[pri:0, instance:Test.profilePageTest@6955cb39]" started-at="2025-05-20T13:58:34 IST" name="verifySuccessfulLogout" description="Logged out successfully" finished-at="2025-05-20T13:58:35 IST" depends-on-methods="Test.profilePageTest.verifyProfilePageLoad" duration-ms="651" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@11eadcba]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLogout -->
      </class> <!-- Test.profilePageTest -->
    </test> <!-- Zygal Connect Mobile App Test Cases -->
  </suite> <!-- Automation Suite -->
</testng-results>
