<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-NB4I6K9" failures="1" tests="13" name="Test.loginPageTest" time="289.804" errors="0" timestamp="2025-05-19T18:05:00 IST" skipped="0">
  <testcase classname="Test.loginPageTest" name="verifyGoToSignPage" time="2.202"/>
  <testcase classname="Test.loginPageTest" name="verifyAccountBlockOnGetOtpPage" time="0.764"/>
  <testcase classname="Test.loginPageTest" name="verifyAdminViewerLoginBlock" time="0.712"/>
  <testcase classname="Test.loginPageTest" name="verifyResendOTP" time="63.804"/>
  <testcase classname="Test.loginPageTest" name="verifySameEmailOnOtpPage" time="0.048"/>
  <testcase classname="Test.loginPageTest" name="loginwithWrongOTP" time="3.657"/>
  <testcase classname="Test.loginPageTest" name="verifyAccountBlock" time="12.206"/>
  <testcase classname="Test.loginPageTest" name="verifyAccountBlockOnResendOtp" time="194.245">
    <failure message="Error message isn&#039;t as expected expected [You have reached the maximum login attempts for the day. Please try again after 24 hours.] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message isn't as expected expected [You have reached the maximum login attempts for the day. Please try again after 24 hours.] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at Test.loginPageTest.verifyAccountBlockOnResendOtp(loginPageTest.java:284)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyAccountBlockOnResendOtp -->
  <testcase classname="Test.loginPageTest" name="loginWithInvalidEmail" time="0.818"/>
  <testcase classname="Test.loginPageTest" name="verifyEmptyUserEmail" time="1.249"/>
  <testcase classname="Test.loginPageTest" name="loginWithNotRegisteredEmail" time="0.678"/>
  <testcase classname="Test.loginPageTest" name="loginWithValidCredentialsTest" time="8.202"/>
  <testcase classname="Test.loginPageTest" name="loginWithInvalidCredentialsTest" time="1.219"/>
</testsuite> <!-- Test.loginPageTest -->
